// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DBConnectionService handles database connection operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $internal from "./internal.js";

/**
 * DeleteConnection removes a connection
 */
export function DeleteConnection(id: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2701863404, id) as any;
    return $resultPromise;
}

/**
 * GetConnections returns all saved connections
 */
export function GetConnections(): Promise<$models.DBConnection[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1719013810) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetDatabaseTables returns all tables in the database for a given connection
 */
export function GetDatabaseTables(connectionID: string): Promise<$models.TableInfo[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(489988417, connectionID) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType3($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * RunQuery executes a query on the specified connection
 */
export function RunQuery(connectionID: string, query: string): Promise<[$internal.columns[], string[][]]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3274057340, connectionID, query) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        $result[0] = $$createType5($result[0]);
        $result[1] = $$createType7($result[1]);
        return $result;
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * SaveConnection adds or updates a connection
 */
export function SaveConnection(connection: $models.DBConnection): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1470639886, connection) as any;
    return $resultPromise;
}

/**
 * TestConnection tests if a connection works
 */
export function TestConnection(connection: $models.DBConnection): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1306896443, connection) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.DBConnection.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.TableInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $internal.columns.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = $Create.Array($$createType6);
