// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class columns {
    "Name": string;
    "Type": string;

    /** Creates a new columns instance. */
    constructor($$source: Partial<columns> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Type" in $$source)) {
            this["Type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new columns instance from a string or object.
     */
    static createFrom($$source: any = {}): columns {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new columns($$parsedSource as Partial<columns>);
    }
}
