// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * DBConnection represents a database connection configuration
 */
export class DBConnection {
    "id": string;
    "name": string;

    /**
     * "postgres" or "mysql"
     */
    "type": string;
    "host": string;
    "port": number;
    "username": string;
    "password": string;
    "database": string;

    /** Creates a new DBConnection instance. */
    constructor($$source: Partial<DBConnection> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DBConnection instance from a string or object.
     */
    static createFrom($$source: any = {}): DBConnection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DBConnection($$parsedSource as Partial<DBConnection>);
    }
}
