// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $internal from "./internal.js";

export function RunSQLQuery(query: string): Promise<[$internal.columns[] | null, string[][] | null]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2259990685, query) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        $result[0] = $$createType2($result[0]);
        $result[1] = $$createType5($result[1]);
        return $result;
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = $internal.columns.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Nullable($$createType4);
